package aiobfs

import (
	"math"
	"math/rand/v2"
	"sync"
)

// exp3 implements a baseline-subtracted variant of the EXP3 adversarial
// multi-armed bandit (Auer et al., "The Nonstochastic Multiarmed Bandit
// Problem"). EXP3 is the right family here because the "reward" (did this
// disguise get through fast and unthrottled?) is being generated by an
// adversary — a censor or traffic-shaping middlebox actively trying to
// detect and penalize the tunnel — not by a fixed stochastic process, and
// its built-in gamma-exploration is what keeps profile choice able to
// change at all instead of collapsing onto one disguise forever.
//
// Vanilla EXP3's multiplicative update (weight *= exp(+estimated reward))
// only ever *increases* the weight of whichever arm was just played, since
// reward is non-negative — an arm that has accumulated a head start keeps
// growing even while performing badly (just more slowly), and a never-yet
// -tried alternative cannot catch up until pure gamma-exploration happens
// to sample it. That made recovery from "the incumbent profile just got
// throttled" unacceptably slow and luck-dependent in testing here. This
// variant subtracts a slowly-tracked reward baseline before exponentiating,
// so an arm performing below the recent average actively *loses* relative
// weight instead of merely gaining it slower. This is a common practical
// variance-reduction technique (baseline-subtracted REINFORCE/bandit
// updates); it trades EXP3's textbook worst-case regret bound for the
// faster, more intuitive "bad news erodes preference" behavior this
// package actually needs.
type exp3 struct {
	mu           sync.Mutex
	weights      []float64
	gamma        float64
	baseline     float64
	baselineRate float64
	rng          *rand.Rand
}

// newExp3 creates a bandit over n arms. gamma controls the exploration
// floor: with probability gamma the next arm is picked uniformly at random
// regardless of learned weights, so no disguise is ever starved to zero and
// none is ever selected deterministically forever. 0.10-0.20 is a
// reasonable range; lower exploits harder, higher explores harder.
func newExp3(n int, gamma float64) *exp3 {
	if n <= 0 {
		panic("aiobfs: exp3 needs at least one arm")
	}
	if gamma <= 0 || gamma > 1 {
		gamma = 0.15
	}
	w := make([]float64, n)
	for i := range w {
		w[i] = 1
	}
	return &exp3{weights: w, gamma: gamma, baseline: 0.5, baselineRate: 0.05, rng: rand.New(cryptoSeededSource())}
}

// probabilities returns the current selection distribution over arms.
func (e *exp3) probabilities() []float64 {
	n := len(e.weights)
	sum := 0.0
	for _, w := range e.weights {
		sum += w
	}
	p := make([]float64, n)
	for i, w := range e.weights {
		p[i] = (1-e.gamma)*(w/sum) + e.gamma/float64(n)
	}
	return p
}

// selectArm samples an arm from the current distribution and returns both
// the arm index and the probability it was drawn with (needed by update to
// form an unbiased reward estimate).
func (e *exp3) selectArm() (arm int, prob float64) {
	e.mu.Lock()
	defer e.mu.Unlock()
	p := e.probabilities()
	return e.sampleLocked(p)
}

// selectArmBiased is like selectArm but additionally applies an external
// multiplicative prior (in log-space) on top of the learned weights before
// sampling — this is how policyNet's feature-conditioned opinion gets
// folded into disguise selection without replacing EXP3's own adaptive
// weighting. bias[i] shifts arm i's log-weight; values are clamped to
// +/-4 to keep a single opinionated forward pass from completely
// overriding weeks of learned bandit weight. It returns the sampled arm,
// the probability it was actually sampled with (the correct importance
// weight for a subsequent update call), and the full distribution (so a
// caller that decides NOT to act on the sample — e.g. because a minimum
// dwell time hasn't elapsed — can still look up the probability of
// whichever arm it keeps using instead).
func (e *exp3) selectArmBiased(bias []float64) (arm int, prob float64, dist []float64) {
	e.mu.Lock()
	defer e.mu.Unlock()

	n := len(e.weights)
	adjusted := make([]float64, n)
	sum := 0.0
	for i, w := range e.weights {
		b := 0.0
		if i < len(bias) {
			b = clampBias(bias[i])
		}
		adjusted[i] = w * math.Exp(b)
		sum += adjusted[i]
	}
	p := make([]float64, n)
	for i, a := range adjusted {
		p[i] = (1-e.gamma)*(a/sum) + e.gamma/float64(n)
	}
	arm, prob = e.sampleLocked(p)
	return arm, prob, p
}

// sampleLocked draws an arm from distribution p. Caller must hold e.mu.
func (e *exp3) sampleLocked(p []float64) (arm int, prob float64) {
	r := e.rng.Float64()
	acc := 0.0
	for i, pi := range p {
		acc += pi
		if r <= acc || i == len(p)-1 {
			return i, pi
		}
	}
	return len(p) - 1, p[len(p)-1]
}

// clampBias bounds an external log-weight bias so a single policy-network
// opinion can steer but never completely override the bandit's own
// track record.
func clampBias(x float64) float64 {
	const limit = 4.0
	if x > limit {
		return limit
	}
	if x < -limit {
		return -limit
	}
	return x
}

// update feeds back an observed reward in [0,1] for the arm that was played
// with the given selection probability. Higher reward = keep favoring this
// disguise; the exp3 update rule automatically decays that preference the
// moment a different arm starts performing better, which is what lets the
// shaper track a censor that adapts mid-session.
func (e *exp3) update(arm int, prob, reward float64) {
	if reward < 0 {
		reward = 0
	} else if reward > 1 {
		reward = 1
	}
	if prob <= 0 {
		prob = 1e-6
	}

	e.mu.Lock()
	defer e.mu.Unlock()

	// Advantage over the running baseline, not raw reward: this is what
	// lets a played arm's weight actually go down when it performs worse
	// than what this bandit has recently come to expect, rather than only
	// ever growing (see the type doc comment for why plain EXP3 isn't
	// enough here).
	advantage := reward - e.baseline
	e.baseline += e.baselineRate * (reward - e.baseline)

	n := len(e.weights)
	estimated := advantage / prob
	exponent := e.gamma * estimated / float64(n)
	// Clamp before exponentiating: a long streak of extreme advantage
	// values could otherwise over/underflow float64, and no single
	// observation should move weight by more than a bounded factor anyway.
	if exponent > 30 {
		exponent = 30
	} else if exponent < -30 {
		exponent = -30
	}
	e.weights[arm] *= math.Exp(exponent)
	if e.weights[arm] < 1e-12 {
		// Keep it strictly positive and recoverable rather than letting it
		// underflow to a hard 0 that no future positive reward could
		// multiply back up from.
		e.weights[arm] = 1e-12
	}

	// Renormalize to prevent unbounded float growth over a long-running
	// session; relative weight ratios are all that matter for selection,
	// so rescaling all weights by the same factor changes nothing else.
	maxW := 0.0
	for _, w := range e.weights {
		if w > maxW {
			maxW = w
		}
	}
	if maxW > 1e100 {
		for i := range e.weights {
			e.weights[i] /= maxW
		}
	}
}

// snapshot returns a copy of the current per-arm weights, for diagnostics.
func (e *exp3) snapshot() []float64 {
	e.mu.Lock()
	defer e.mu.Unlock()
	out := make([]float64, len(e.weights))
	copy(out, e.weights)
	return out
}
